FROM node:22-alpine AS builder

WORKDIR /usr/src/app/app-ui/

COPY . . 

ENV NODE_OPTIONS=--openssl-legacy-provider

RUN npm install && npm run build -- --prod

FROM nginx:alpine AS angular-ui

COPY --from=builder /usr/src/app/app-ui/dist/angular-nodejs-example /usr/share/nginx/html

EXPOSE 80